openapi: "3.0.0"

info:
  title: Administration App User
  version: "1.0.0"
  description: AppUser part of Adminstration app API

servers:
  - url: http://localhost:8080/

tags:
  - name: AppUser
    description: appuser specific data.
paths:
  /user:
    get:
      tags:
        - AppUser
      summary: Get All AppUsers
      operationId: getUsers
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                type: array  # Return a list of AppRoleDto
                items:
                  $ref: '../model/app-user/AppUserResp.yml'
        '404':
          description: NOT FOUND
        '400':
          description: BAD REQUEST
    post:
      tags:
        - AppUser
        - create
        - save
        - Posts
      summary: Create an AppUser
      operationId: createAppUSer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../model/app-user/AppUserRequest.yml'
            example:
              prenom: Youssoupha
              nom: Faye
              email: youssoupha@groupeisi.com
              motDepasse: P@sser1234
              etat: 0
              appRoleIds: [1,3]
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                type: array  # Return a list of AppRoleDto
                items:
                  $ref: '../model/app-user/AppUserResp.yml'
        '400':
          description: BAD REQUEST
  /user-reference:
    get:
      tags:
        - AppUserByID
        - findUser
        - Gets
      summary: find One By id
      operationId: getAppUserById
      responses:
        200:
          description: SUCCESS
          content:
            'application/json':
              schema:
                $ref: '../model/app-user/AppUserResp.yml'
    put:
      tags:
        - AppUser
        - Puts
      summary: Update an AppRole
      operationId: updateRole
      requestBody:
        content:
          application/json:
            schema:
              $ref: '../model/app-user/AppUserRequest.yml'
      responses:
        '200':
          description: SUCCESS
          content:
            application/json:
              schema:
                type: array  # Return a list of AppRoleDto
                items:
                  $ref: '../model/app-user/AppUserResp.yml'
        '404':
          description: NOT FOUND
        '400':
          description: BAD REQUEST
    delete:
      tags:
        - AppRole
        - Deletes
      summary: Delete an AppRole
      operationId: deleteRole
      responses:
        '200':
          description: SUCCESS
        '204':
          description: No Content
        '404':
          description: NOT FOUND